apiVersion: v1
kind: Secret
metadata:
  name: laravel-in-kubernetes
type: Opaque
stringData:
  APP_KEY: ""

  DB_USERNAME: "kubernetes_db_user"
  DB_PASSWORD: ""

  REDIS_PASSWORD: ""

  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"

  TRUSTUP_SERVER_AUTHORIZATION: ""