apiVersion: v1
kind: ConfigMap
metadata:
  name: task-trustup-io
data:
  APP_NAME: "task.trustup.io"
  APP_ENV: "local"
  APP_DEBUG: "true"
  APP_URL: "https://task.trustup.io"

  LOG_CHANNEL: "stdout"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "task-trustup-io-do-user-3877774-0.b.db.ondigitalocean.com"
  DB_PORT: "25060"
  DB_DATABASE: "kubernetes_db"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"

  REDIS_HOST: "task-trustup-io-redis"
  REDIS_PORT: "6379"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  # DO_DEFAULT_REGION: "ams3"
  # DO_BUCKET: "trustup-io-media"
  # DO_ENDPOINT: "https://ams3.digitaloceanspaces.com/"
  # DO_USE_PATH_STYLE_ENDPOINT: "false"

  PUSHER_APP_ID: ""
  PUSHER_HOST: ""
  PUSHER_PORT: "443"
  PUSHER_SCHEME: "https"
  PUSHER_APP_CLUSTER: "mt1"

  VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  VITE_PUSHER_HOST: "${PUSHER_HOST}"
  VITE_PUSHER_PORT: "${PUSHER_PORT}"
  VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
  VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

  SCOUT_DRIVER: "meilisearch"
  MEILISEARCH_HOST: "http://meilisearch:7700"

  TRUSTUP_MESSAGING_API_URL: "https://messaging.trustup.io/api"
  TRUSTUP_MESSAGING_APP_KEY: "trustup-io-task"
  TRUSTUP_AUTH_IO_URL: "https://auth.trustup.io"
