apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-trustup-io-cron
  labels:
    tier: backend
    layer: cron
  annotations:
    configmap.reloader.stakater.com/reload: "task-trustup-io"
    secret.reloader.stakater.com/reload: "task-trustup-io"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: cron
  template:
    metadata:
      labels:
        tier: backend
        layer: cron
    spec:
      containers:
        - name: cron
          image: henrotaym/task-trustup-io-cron:0.0.1
          envFrom:
            - configMapRef:
                name: task-trustup-io
            - secretRef:
                name: task-trustup-io