apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-trustup-io-redis
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # We are starting with 1GB. We can always increase it later.
      storage: 1Gi