apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-trustup-io-fpm
  labels:
    tier: backend
    layer: fpm
  annotations:
    configmap.reloader.stakater.com/reload: "task-trustup-io"
    secret.reloader.stakater.com/reload: "task-trustup-io"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: migrations
          image: henrotaym/task-trustup-io-cli:0.0.1
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: task-trustup-io
            - secretRef:
                name: task-trustup-io
      containers:
        - name: fpm
          image: henrotaym/task-trustup-io-fpm:0.0.1
          ports:
            - containerPort: 9000
          command: ["/bin/sh"]
          args: ["-c", "php artisan event:cache && \
            php artisan route:cache && \
            php artisan view:cache && \
            exec php-fpm"]
          envFrom:
            - configMapRef:
                name: task-trustup-io
            - secretRef:
                name: task-trustup-io